# === TAHAP 1: Proses Build ===
FROM node:22-alpine AS builder

WORKDIR /app

# Aktifkan pnpm
RUN corepack enable && corepack prepare pnpm@latest --activate

# Copy seluruh monorepo
COPY . .

# TAMBAHKAN BARIS INI (Paksa Rollup untuk mengenali Alpine Linux)
ENV npm_config_platform=linux
ENV npm_config_architecture=x64
ENV npm_config_libc=musl

# Install dependencies
RUN pnpm install --no-frozen-lockfile

# Build khusus aplikasi frontend (Vite)
RUN pnpm --filter ste-app... run build


# === TAHAP 2: Server Produksi (Sangat Ringan) ===
FROM node:22-alpine

WORKDIR /app

# Install 'serve'
RUN npm install -g serve

# Ambil HANYA folder hasil build (dist) dari Tahap 1
COPY --from=builder /app/artifacts/ste-app/dist ./dist

# Jalankan server
CMD ["sh", "-c", "serve -s dist -l tcp://0.0.0.0:${PORT:-8080}"]