kind = "web"
previewPath = "/"
title = "STE - Sistem Transaksi Elektronik"
version = "1.0.0"
id = "artifacts/ste-app"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19472

[services.development]
run = "pnpm --filter @workspace/ste-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/ste-app", "run", "build" ]
publicDir = "artifacts/ste-app/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19472"
BASE_PATH = "/"
